### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by robertmclaws** [CloudNimble/BlazorEssentials#1]
Work remaining on this feature:

- [x] Login redirect generation
- [x] Token processing
- [x] Logout processing
- [x] Authorization checks
- [ ] Automatic `StateHasChanged` wireup 

Current status: Have an OK pattern for checking authotization, but it could be better.

**Comment by Code-DJ** [comment]
Will this work with popup windows?

**Comment by robertmclaws** [comment]
Hey @Code-DJ, so we have deprecated our authentication in favor of Microsoft's built-in process. At the time I wrote this feature, they didn't have any auth capability, and now they do.

Going to close this now, if you have any other questions, please let me know. Thanks!
