### ISSUE TITLE
Documentaion & Wiki

### ISSUE THREAD

**Issue by gptucci** [CloudNimble/BlazorEssentials#3]
Hi
where can I find some documentation about this library ? Tnx

**Comment by robertmclaws** [comment]
Hey! Apologies, we don't have any documentation for the library yet. You can check out the sample here: https://github.com/CloudNimble/BlazorEssentials/tree/master/src/CloudNimble.BlazorEssentials.TestApp, it walks you through the basic elements of building MVVM apps using Blazor. It also has controls for building dynamic menus and other stuff like that.

Happy to answer questions and help any way I can. Thanks!
